# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-Taller1-MPU9250.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# ------------------------------------------------------------
#               LIBRERIAS
# ------------------------------------------------------------
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtWidgets import QComboBox
import serial
import serial.tools.list_ports
import numpy 
import time
import sys
import pyqtgraph as pg
from pyqtgraph import PlotWidget
import IMG_rc

# ------------------------------------------------------------
#               CONFIGURACION DE PYGAME
# ------------------------------------------------------------
# Configurar fondo blanco y texto/ejes negros para TODAS las gráficas
pg.setConfigOption('background', 'w')
pg.setConfigOption('foreground', 'k')

# ------------------------------------------------------------
#               CONSTANTES
# ------------------------------------------------------------
# CONSTANTES DE SENSIBILIDAD
SENSITIVITY_ACCEL = 2.0/32768.0     # (g)
SENSITIVITY_GYRO  = 250.0/32768.0   # (°/s)
SENSITIVITY_MAG   = 4800.0/32768.0  # (µT/LSB)

# ------------------------------------------------------------
#               CLASES
# ------------------------------------------------------------
class OutputRedirector: # Monitor Serial 
    def __init__(self, text_widget):
        self.text_widget = text_widget
        self.stdout_orig = sys.stdout

    def write(self, text):
        self.stdout_orig.write(text)
        if text.strip():
            self.text_widget.moveCursor(self.text_widget.textCursor().MoveOperation.End)
            self.text_widget.insertPlainText(text + "\n")
            self.text_widget.moveCursor(self.text_widget.textCursor().MoveOperation.End)

    def flush(self):
        self.stdout_orig.flush()

class Ui_Form(object): # Interfaz Gráfica de Usuario
    def setupUi(self, Form):
        #-----------------------------------------------------------
        #               VARIABLES DE CALIBRACION
        #-----------------------------------------------------------
        self.GirAceCalibrado = False  # Variable para controlar el estado de calibración
        self.MagXCalibrado = False
        self.MagYCalibrado = False  # Variable para controlar el estado de calibración
        self.MagZCalibrado = False  # Variable para controlar el estado de calibración
        self.off_ax = 0.0
        self.off_ay = 0.0
        self.off_az = 0.0
        self.off_gx = 0.0
        self.off_gy = 0.0
        self.off_gz = 0.0
        self.off_mx = 0.0
        self.off_my = 0.0
        self.off_mz = 0.0

        #------------------------------------------------------------
        #               CONFIGURACION DE LA INTERFAZ
        #------------------------------------------------------------
        Form.setObjectName("Form")
        Form.resize(1072, 712)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(710, 570, 221, 121))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 341, 661))
        self.groupBox.setObjectName("groupBox")
        self.GiroscopioNoCalibrado = PlotWidget(self.groupBox)
        self.GiroscopioNoCalibrado.setGeometry(QtCore.QRect(10, 40, 321, 191))
        self.GiroscopioNoCalibrado.setObjectName("GiroscopioNoCalibrado")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 440, 71, 16))
        self.label_6.setObjectName("label_6")
        self.AcelerometroNoCalibrado = PlotWidget(self.groupBox)
        self.AcelerometroNoCalibrado.setGeometry(QtCore.QRect(10, 250, 321, 191))
        self.AcelerometroNoCalibrado.setObjectName("AcelerometroNoCalibrado")
        self.MagnetometroNoCalibrado = PlotWidget(self.groupBox)
        self.MagnetometroNoCalibrado.setGeometry(QtCore.QRect(10, 460, 321, 191))
        self.MagnetometroNoCalibrado.setObjectName("MagnetometroNoCalibrado")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 301, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 1071, 41))
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 40, 341, 661))
        self.groupBox_2.setObjectName("groupBox_2")
        self.GiroscopioNoCalibrado_2 = PlotWidget(self.groupBox_2)
        self.GiroscopioNoCalibrado_2.setGeometry(QtCore.QRect(10, 40, 321, 191))
        self.GiroscopioNoCalibrado_2.setObjectName("GiroscopioNoCalibrado_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 440, 71, 16))
        self.label_9.setObjectName("label_9")
        self.AcelerometroNoCalibrado_2 = PlotWidget(self.groupBox_2)
        self.AcelerometroNoCalibrado_2.setGeometry(QtCore.QRect(10, 250, 321, 191))
        self.AcelerometroNoCalibrado_2.setObjectName("AcelerometroNoCalibrado_2")
        self.MagnetometroNoCalibrado_2 = PlotWidget(self.groupBox_2)
        self.MagnetometroNoCalibrado_2.setGeometry(QtCore.QRect(10, 460, 321, 191))
        self.MagnetometroNoCalibrado_2.setObjectName("MagnetometroNoCalibrado_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(710, 370, 351, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.GiroscopioNoCalibrado_4 = PlotWidget(self.groupBox_3)
        self.GiroscopioNoCalibrado_4.setGeometry(QtCore.QRect(10, 20, 321, 211))
        self.GiroscopioNoCalibrado_4.setObjectName("GiroscopioNoCalibrado_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(710, 40, 351, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(710, 150, 351, 221))
        self.groupBox_5.setObjectName("groupBox_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 110, 331, 101))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 86))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.label.raise_()
        self.groupBox.raise_()
        self.label_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.label_2.raise_()

        self.puerto_serial = None
        self.groupBox.setEnabled(False)
        self.groupBox_2.setEnabled(False)
        self.groupBox_3.setEnabled(False)
        self.groupBox_5.setEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        sys.stdout = OutputRedirector(self.plainTextEdit)
        self.comboBox.showPopup = self.on_combobox_click
        self.comboBox_2.setEnabled(False)
        self.comboBox_3.setEnabled(False)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox_2.setEnabled(False)
        self.pushButton.setEnabled(False)
        self.pushButton.clicked.connect(self.AdquirirMag)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.clicked.connect(self.ConectarPuerto)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.clicked.connect(self.DesconectarPuerto)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.clicked.connect(self.AdquirirGirAce)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.clicked.connect(self.CalibrarMagXY)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.clicked.connect(self.CalibrarGirAce)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.clicked.connect(self.CalibrarMagZ)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.clicked.connect(self.AdquirirTodo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    #------------------------------------------------------------
    #               FUNCIONES DE LA INTERFAZ
    #------------------------------------------------------------
    def AdquirirMag(self):
        self.groupBox_4.setEnabled(False)
        self.groupBox_5.setEnabled(False)

        self.Adquirir()
        self.datosMag = self.datos.copy()

        if self.i > 0:
            self.RecMag = True
            self.datosMag = self.datos.copy()
            self.datosMag = numpy.delete(self.datos.copy(), [2, 3, 4, 5, 6, 7], axis=1) # Elimina las columnas 2, 3, 4, 5, 6 y 7 (GirosCopio y Acelerómetro)
            delta_t = self.datos[:, 1] # Extraer la columna de deltas de tiempo (asumiendo columna index 1)
            tiempo_transcurrido = numpy.cumsum(delta_t).reshape(-1, 1) # Calcular la suma acumulada (tiempo total acumulado)
            self.datosMag = numpy.hstack((self.datosMag, tiempo_transcurrido)) # Añadir la nueva columna al final

            print(f"\nLectura finalizada. Muestras procesadas: {self.i}")
            print(f"Tiempo teorico total de adquisición: {tiempo_transcurrido[-1][0]:.2f} ms")
            print(f"Tiempo teorico promedio entre muestras: {1000.0 * numpy.mean(delta_t):.2f} ms")
            print(f"Frecuencia teorica de muestreo promedio: {1.0 / numpy.mean(delta_t):.2f} Hz")
            print(f"Datos de Magnetómetro:\n")
            for fila in self.datosMag:
                # Formatea cada número con 2 decimales y espacio fijo de 9 caracteres
                fila_texto = " ".join([f"{val:9.2f}" for val in fila])
                print(fila_texto)

            self.eje_x = self.datosMag[:self.i, 0] if numpy.max(self.datosMag[:self.i, 0]) > 0 else numpy.arange(self.i)

            # Extraer columnas RAW
            self.mag_x_raw  = self.datosMag[:self.i, 2]
            self.mag_y_raw  = self.datosMag[:self.i, 3]
            self.mag_z_raw  = self.datosMag[:self.i, 4]

            self.EscalamientoFisico()

        self.groupBox_4.setEnabled(True)
        self.groupBox_5.setEnabled(True)

    def AdquirirGirAce(self):
        self.groupBox_4.setEnabled(False)
        self.groupBox_5.setEnabled(False)

        self.Adquirir()

        if self.i > 0:
            self.RecGirAce = True
            self.datosGirAce = self.datos.copy()
            self.datosGirAce = numpy.delete(self.datos.copy(), [8, 9, 10], axis=1) # Elimina las columnas 8, 9 y 10 (Magnetómetro)
            delta_t = self.datos[:, 1] # Extraer la columna de deltas de tiempo (asumiendo columna index 1)
            tiempo_transcurrido = numpy.cumsum(delta_t).reshape(-1, 1) # Calcular la suma acumulada (tiempo total acumulado)
            self.datosGirAce = numpy.hstack((self.datosGirAce, tiempo_transcurrido)) # Añadir la nueva columna al final

            print(f"\nLectura finalizada. Muestras procesadas: {self.i}")
            print(f"Tiempo teorico total de adquisición: {tiempo_transcurrido[-1][0]:.2f} ms")
            print(f"Tiempo teorico promedio entre muestras: {1000.0 * numpy.mean(delta_t):.2f} ms")
            print(f"Frecuencia teorica de muestreo promedio: {1.0 / numpy.mean(delta_t):.2f} Hz")
            print(f"Datos de Giroscopio y Acelerómetro:\n")
            for fila in self.datosGirAce:
                # Formatea cada número con 2 decimales y espacio fijo de 9 caracteres
                fila_texto = " ".join([f"{val:9.2f}" for val in fila])
                print(fila_texto)



            eje_x = self.datosGirAce[:self.i, 0] if numpy.max(self.datosGirAce[:self.i, 0]) > 0 else numpy.arange(self.i)

            # Extraer columnas RAW
            self.acc_x_raw  = self.datosGirAce[:self.i, 2]
            self.acc_y_raw  = self.datosGirAce[:self.i, 3]
            self.acc_z_raw  = self.datosGirAce[:self.i, 4]
            self.gyro_x_raw = self.datosGirAce[:self.i, 5]
            self.gyro_y_raw = self.datosGirAce[:self.i, 6]
            self.gyro_z_raw = self.datosGirAce[:self.i, 7]   

            self.EscalamientoFisico()  
        else:
            print("No se recibieron datos válidos del MPU9250.")

        self.groupBox_4.setEnabled(True)
        self.groupBox_5.setEnabled(True)

    def AdquirirTodo(self): 
        self.groupBox_4.setEnabled(False)
        self.groupBox_5.setEnabled(False)

        self.Adquirir()

        if self.i > 0:
            self.RecGirAce = True
            self.RecMag = True
            delta_t = self.datos[:, 1] # Extraer la columna de deltas de tiempo (asumiendo columna index 1)
            tiempo_transcurrido = numpy.cumsum(delta_t).reshape(-1, 1) # Calcular la suma acumulada (tiempo total acumulado)
            self.datos = numpy.hstack((self.datos, tiempo_transcurrido)) # Añadir la nueva columna al final

            print(f"\nLectura finalizada. Muestras procesadas: {self.i}")
            print(f"Tiempo teorico total de adquisición: {tiempo_transcurrido[-1][0]:.2f} ms")
            print(f"Tiempo teorico promedio entre muestras: {1000.0 * numpy.mean(delta_t):.2f} ms")
            print(f"Frecuencia teorica de muestreo promedio: {1.0 / numpy.mean(delta_t):.2f} Hz")
            print(f"Datos de Giroscopio y Acelerómetro:\n")
            for fila in self.datos:
                # Formatea cada número con 2 decimales y espacio fijo de 9 caracteres
                fila_texto = " ".join([f"{val:9.2f}" for val in fila])
                print(fila_texto)



            eje_x = self.datos[:self.i, 0] if numpy.max(self.datos[:self.i, 0]) > 0 else numpy.arange(self.i)

            # Extraer columnas RAW
            self.acc_x_raw  = self.datos[:self.i, 2]
            self.acc_y_raw  = self.datos[:self.i, 3]
            self.acc_z_raw  = self.datos[:self.i, 4]
            self.gyro_x_raw = self.datos[:self.i, 5]
            self.gyro_y_raw = self.datos[:self.i, 6]
            self.gyro_z_raw = self.datos[:self.i, 7]     
            self.mag_x_raw  = self.datos[:self.i, 8]
            self.mag_y_raw  = self.datos[:self.i, 9]
            self.mag_z_raw  = self.datos[:self.i, 10]

        else:
            print("No se recibieron datos válidos del MPU9250.")
        self.groupBox_4.setEnabled(True)
        self.groupBox_5.setEnabled(True)

    def CalibrarGirAce(self):
        if self.i > 0:
            # -------------------------------------------------------------
            # 1. CÁLCULO DE OFFSETS (RAW LSB)
            # -------------------------------------------------------------
            self.off_ax = numpy.mean(self.acc_x_raw)
            self.off_ay = numpy.mean(self.acc_y_raw)
            self.off_az = numpy.mean(self.acc_z_raw) - (1.0 / SENSITIVITY_ACCEL)
            self.off_gx = numpy.mean(self.gyro_x_raw)
            self.off_gy = numpy.mean(self.gyro_y_raw)
            self.off_gz = numpy.mean(self.gyro_z_raw)

            self.GirAceCalibrado = True  # Marcar como calibrado

            print("=" * 55)
            print("          OFFSETS CALCULADOS          ")
            print("=" * 55)
            print(f" Accel X : {self.off_ax:10.2f} LSB  ({self.off_ax * SENSITIVITY_ACCEL:6.3f} g)")
            print(f" Accel Y : {self.off_ay:10.2f} LSB  ({self.off_ay * SENSITIVITY_ACCEL:6.3f} g)")
            print(f" Accel Z : {self.off_az:10.2f} LSB  ({self.off_az * SENSITIVITY_ACCEL:6.3f} g)")
            print("-" * 55)
            print(f" Gyro  X : {self.off_gx:10.2f} LSB  ({self.off_gx * SENSITIVITY_GYRO:6.2f} °/s)")
            print(f" Gyro  Y : {self.off_gy:10.2f} LSB  ({self.off_gy * SENSITIVITY_GYRO:6.2f} °/s)")
            print(f" Gyro  Z : {self.off_gz:10.2f} LSB  ({self.off_gz * SENSITIVITY_GYRO:6.2f} °/s)")
            print("=" * 55 + "\n")

    def CalibrarMagXY(self):
        if self.i > 0:
            # -------------------------------------------------------------
            # 1. CÁLCULO DE OFFSETS (RAW LSB)
            # -------------------------------------------------------------
            self.off_mx = numpy.mean(self.mag_x_raw)
            self.off_my = numpy.mean(self.mag_y_raw)
      
            self.MagXYCalibrado = True  # Marcar como calibrado

            print("=" * 55)
            print("          OFFSETS CALCULADOS          ")
            print("=" * 55)
            print(f" Mag   X : {self.off_mx:10.2f} LSB  ({self.off_mx * SENSITIVITY_MAG:6.2f} µT)")
            print(f" Mag   Y : {self.off_my:10.2f} LSB  ({self.off_my * SENSITIVITY_MAG:6.2f} µT)")
            print("=" * 55 + "\n")

    def CalibrarMagZ(self):
        if self.i > 0:
            # -------------------------------------------------------------
            # 1. CÁLCULO DE OFFSETS (RAW LSB)
            # -------------------------------------------------------------
            self.off_mz = numpy.mean(self.mag_z_raw)

            self.MagZCalibrado = True  # Marcar como calibrado

            print("=" * 55)
            print("          OFFSETS CALCULADOS          ")
            print("=" * 55)
            print(f" Mag   Z : {self.off_mz:10.2f} LSB  ({self.off_mz * SENSITIVITY_MAG:6.2f} µT)")
            print("=" * 55 + "\n")

    def CalcularAngulosEuler(self, eje_x):
        # Verificamos que existan los datos calibrados
        if not hasattr(self, 'acc_x_cal') or not hasattr(self, 'mag_x_cal'):
            print("Por favor, calibra los datos antes de calcular los ángulos de Euler.")
            return

        # 1. Calcular Roll y Pitch en radianes usando el Acelerómetro
        self.roll_rad = numpy.arctan2(self.acc_y_cal, self.acc_z_cal)
        self.pitch_rad = numpy.arctan2(-self.acc_x_cal, numpy.sqrt(self.acc_y_cal**2 + self.acc_z_cal**2))

        # 2. Compensación de inclinación para el Magnetómetro (Tilt Compensation)
        mag_x_comp = (self.mag_x_cal * numpy.cos(self.pitch_rad) + 
                      self.mag_z_cal * numpy.sin(self.pitch_rad))
        
        mag_y_comp = (self.mag_x_cal * numpy.sin(self.roll_rad) * numpy.sin(self.pitch_rad) + 
                      self.mag_y_cal * numpy.cos(self.roll_rad) - 
                      self.mag_z_cal * numpy.sin(self.roll_rad) * numpy.cos(self.pitch_rad))

        # 3. Calcular Yaw en radianes
        self.yaw_rad = numpy.arctan2(-mag_y_comp, mag_x_comp)

        # 4. Convertir radianes a grados para visualización
        self.roll_deg = numpy.degrees(self.roll_rad)
        self.pitch_deg = numpy.degrees(self.pitch_rad)
        self.yaw_deg = numpy.degrees(self.yaw_rad)

        # 5. Graficar en la interfaz (usamos GiroscopioNoCalibrado_4 que está en groupBox_3)
        pen_r = pg.mkPen(color='r', width=1.5)
        pen_g = pg.mkPen(color='g', width=1.5)
        pen_b = pg.mkPen(color='b', width=1.5)

        self.GiroscopioNoCalibrado_4.clear()
        self.GiroscopioNoCalibrado_4.addLegend(labelTextSize='8pt', offset=(-11, 11))
        self.GiroscopioNoCalibrado_4.setLabel('left', 'Ángulo', units='°')
        self.GiroscopioNoCalibrado_4.setLabel('bottom', 'Muestras')
        
        self.GiroscopioNoCalibrado_4.plot(eje_x, self.roll_deg, pen=pen_r, name="Roll")
        self.GiroscopioNoCalibrado_4.plot(eje_x, self.pitch_deg, pen=pen_g, name="Pitch")
        self.GiroscopioNoCalibrado_4.plot(eje_x, self.yaw_deg, pen=pen_b, name="Yaw")

    def EscalamientoFisico(self):
        if self.RecMag:
            # NO CALIBRADOS
            self.mag_x_nocal = self.mag_x_raw * SENSITIVITY_MAG
            self.mag_y_nocal = self.mag_y_raw * SENSITIVITY_MAG
            self.mag_z_nocal = self.mag_z_raw * SENSITIVITY_MAG

            self.scale_x = (numpy.max(self.mag_x_nocal) - numpy.min(self.mag_x_nocal))/2
            self.scale_y = (numpy.max(self.mag_y_nocal) - numpy.min(self.mag_y_nocal))/2
            self.scale_z = (numpy.max(self.mag_z_nocal) - numpy.min(self.mag_z_nocal))/2

            # CALIBRADOS
            if self.MagXCalibrado:
                self.mag_x_cal = (self.mag_x_raw - self.off_mx) * self.scale_x / SENSITIVITY_MAG

            if self.MagYCalibrado:
                self.mag_y_cal = (self.mag_y_raw - self.off_my) * self.scale_y / SENSITIVITY_MAG
                
            if self.MagZCalibrado:
                self.mag_z_cal = (self.mag_z_raw - self.off_mz) * self.scale_z / SENSITIVITY_MAG

        if self.RecGirAce:
            # NO CALIBRADOS
            self.acc_x_nocal = self.acc_x_raw * SENSITIVITY_ACCEL
            self.acc_y_nocal = self.acc_y_raw * SENSITIVITY_ACCEL
            self.acc_z_nocal = self.acc_z_raw * SENSITIVITY_ACCEL

            self.gyro_x_nocal = self.gyro_x_raw * SENSITIVITY_GYRO
            self.gyro_y_nocal = self.gyro_y_raw * SENSITIVITY_GYRO
            self.gyro_z_nocal = self.gyro_z_raw * SENSITIVITY_GYRO

            if self.GirAceCalibrado:
                # CALIBRADOS
                self.acc_x_cal = (self.acc_x_raw - self.off_ax) * SENSITIVITY_ACCEL
                self.acc_y_cal = (self.acc_y_raw - self.off_ay) * SENSITIVITY_ACCEL
                self.acc_z_cal = (self.acc_z_raw - self.off_az) * SENSITIVITY_ACCEL

                self.gyro_x_cal = (self.gyro_x_raw - self.off_gx) * SENSITIVITY_GYRO
                self.gyro_y_cal = (self.gyro_y_raw - self.off_gy) * SENSITIVITY_GYRO
                self.gyro_z_cal = (self.gyro_z_raw - self.off_gz) * SENSITIVITY_GYRO

            self.pushButton_6.setEnabled(True)  # Habilitar el botón de calibración de Giroscopio y Acelerómetro

        self.Graficar()

    def Graficar(self):
        self.groupBox.setEnabled(True)
        self.groupBox_2.setEnabled(True)

        styles = {'color': '#000000', 'font-size': '10px'}

        pen_r = pg.mkPen(color='r', width=1.5)
        pen_g = pg.mkPen(color='g', width=1.5)
        pen_b = pg.mkPen(color='b', width=1.5)

        if self.RecGirAce:
            self.RecMag = False

            # --- NO CALIBRADOS ---
            # Giroscopio
            self.GiroscopioNoCalibrado.clear()
            self.GiroscopioNoCalibrado.addLegend(labelTextSize='8pt', offset=(-15, 15))
            self.GiroscopioNoCalibrado.setLabel('left', 'Vel. Angular', units='°/s',)
            self.GiroscopioNoCalibrado.setLabel('bottom', 'Muestras')       
            self.GiroscopioNoCalibrado.plot(eje_x, self.gyro_x_nocal, pen=pen_r, name="gx")
            self.GiroscopioNoCalibrado.plot(eje_x, self.gyro_y_nocal, pen=pen_g, name="gy")
            self.GiroscopioNoCalibrado.plot(eje_x, self.gyro_z_nocal, pen=pen_b, name="gz")

            # Acelerómetro
            self.AcelerometroNoCalibrado.clear()
            self.AcelerometroNoCalibrado.addLegend(labelTextSize='8pt', offset=(-11, 11))
            self.AcelerometroNoCalibrado.setLabel('left', 'Aceleración', units='g')
            self.AcelerometroNoCalibrado.setLabel('bottom', 'Muestras')
            self.AcelerometroNoCalibrado.plot(eje_x, self.acc_x_nocal, pen=pen_r, name="ax")
            self.AcelerometroNoCalibrado.plot(eje_x, self.acc_y_nocal, pen=pen_g, name="ay")
            self.AcelerometroNoCalibrado.plot(eje_x, self.acc_z_nocal, pen=pen_b, name="az")

     
            # --- CALIBRADOS ---
            if self.GirAceCalibrado:
                # Giroscopio Calibrado
                self.GiroscopioNoCalibrado_2.clear()
                self.GiroscopioNoCalibrado_2.addLegend(labelTextSize='8pt', offset=(-11, 11))
                self.GiroscopioNoCalibrado_2.addLegend(labelTextSize='8pt', offset=(-11, 11))
                self.GiroscopioNoCalibrado_2.setLabel('left', 'Aceleración', units='g')
                self.GiroscopioNoCalibrado_2.setLabel('bottom', 'Muestras')
                self.GiroscopioNoCalibrado_2.plot(eje_x, self.gyro_x_cal, pen=pen_r, name="gx cal")
                self.GiroscopioNoCalibrado_2.plot(eje_x, self.gyro_y_cal, pen=pen_g, name="gy cal")
                self.GiroscopioNoCalibrado_2.plot(eje_x, self.gyro_z_cal, pen=pen_b, name="gz cal")

                # Acelerómetro Calibrado
                self.AcelerometroNoCalibrado_2.clear()
                self.AcelerometroNoCalibrado_2.addLegend(labelTextSize='8pt', offset=(-11, 11))
                self.AcelerometroNoCalibrado_2.setLabel('left', 'Aceleración', units='g')
                self.AcelerometroNoCalibrado_2.setLabel('bottom', 'Muestras')
                self.AcelerometroNoCalibrado_2.plot(eje_x, self.acc_x_cal, pen=pen_r, name="ax cal")
                self.AcelerometroNoCalibrado_2.plot(eje_x, self.acc_y_cal, pen=pen_g, name="ay cal")
                self.AcelerometroNoCalibrado_2.plot(eje_x, self.acc_z_cal, pen=pen_b, name="az cal")

        if self.RecMag:
            self.RecGirAce = False

            # --- NO CALIBRADOS ---
            # Magnetómetro
            self.MagnetometroNoCalibrado.clear()
            self.MagnetometroNoCalibrado.addLegend(labelTextSize='8pt')
            self.MagnetometroNoCalibrado.plot(self.mag_y_nocal, self.mag_x_nocal, pen=pen_r, name="mx")
            self.MagnetometroNoCalibrado.plot(self.mag_z_nocal, self.mag_y_nocal, pen=pen_g, name="my")
            self.MagnetometroNoCalibrado.plot(self.mag_z_nocal, self.mag_x_nocal, pen=pen_b, name="mz")

            # --- CALIBRADOS ---
            # Magnetómetro Calibrado
            if self.MagYCalibrado or self.MagZCalibrado:
                self.MagnetometroNoCalibrado_2.clear()
                self.MagnetometroNoCalibrado_2.addLegend(labelTextSize='8pt')
                self.MagnetometroNoCalibrado_2.plot(self.eje_x, self.mag_x_cal, pen=pen_r, name="mx cal")
                self.MagnetometroNoCalibrado_2.plot(self.eje_x, self.mag_y_cal, pen=pen_g, name="my cal")
                self.MagnetometroNoCalibrado_2.plot(self.eje_x, self.mag_z_cal, pen=pen_b, name="mz cal")

                self.CalcularAngulosEuler(self.eje_x)

    def ConectarPuerto(self):
        self.groupBox_5.setEnabled(True)

        if not self.puerto_serial or not self.puerto_serial.is_open:
            puerto_nom = self.ObtenerPuertoSeleccionado()
            
            if not puerto_nom or puerto_nom == "No hay puertos disponibles":
                print("Selecciona un puerto válido antes de conectar.")
                return

            try:
                self.puerto_serial = serial.Serial(
                    port=puerto_nom,
                    baudrate=int(self.comboBox_2.currentData()),
                    timeout=self.doubleSpinBox.value()
                )
                time.sleep(1)
                self.puerto_serial.reset_input_buffer()
                
                self.pushButton.setEnabled(True)
                self.pushButton_2.setEnabled(False)
                self.pushButton_3.setEnabled(True)
                self.pushButton_4.setEnabled(True)
                if self.MagYCalibrado:
                    self.pushButton_5.setEnabled(True)
                if self.MagZCalibrado:
                    self.pushButton_7.setEnabled(True)
                if self.GirAceCalibrado:
                    self.pushButton_6.setEnabled(True)
                self.pushButton_8.setEnabled(True)
                self.comboBox.setEnabled(False)
                self.comboBox_2.setEnabled(False)
                self.comboBox_3.setEnabled(True)
                self.comboBox_3.clear()
                self.comboBox_3.addItem("50", userData=50)
                self.comboBox_3.addItem("100", userData=100)
                self.comboBox_3.addItem("200", userData=200)
                self.comboBox_3.addItem("300", userData=300)
                self.comboBox_3.setCurrentIndex(3)
                self.doubleSpinBox.setEnabled(False)
                self.doubleSpinBox_2.setEnabled(True)
                self.doubleSpinBox_2.setValue(20.0)
                
                print(f"--- Conectado exitosamente a {puerto_nom} ---")

            except serial.SerialException as e:
                print(f"Error al abrir el puerto {puerto_nom}: {e}")

    def DesconectarPuerto(self):
        if self.puerto_serial and self.puerto_serial.is_open:
            try:
                self.puerto_serial.close()
                self.puerto_serial = None
                
                self.comboBox.setEnabled(True)
                self.comboBox_2.setEnabled(True)
                self.comboBox_3.setEnabled(False)
                self.doubleSpinBox.setEnabled(True)
                self.doubleSpinBox_2.setEnabled(False)
                self.pushButton.setEnabled(False)
                self.pushButton_2.setEnabled(True)
                self.pushButton_3.setEnabled(False)
                self.pushButton_4.setEnabled(False)
                self.pushButton_5.setEnabled(False)
                self.pushButton_6.setEnabled(False)
                self.pushButton_7.setEnabled(False)
                self.pushButton_8.setEnabled(False)
                
                print("--- Puerto Desconectado ---")
            except Exception as e:
                print(f"Error al cerrar el puerto: {e}")

    def Adquirir(self):
        if not self.puerto_serial or not self.puerto_serial.is_open:
            print("Puerto serial no disponible.")
            return

        self.raw = int(self.comboBox_3.currentText())
        # 11 columnas: [index, timer, ax, ay, az, gx, gy, gz, mx, my, mz]
        self.datos = numpy.zeros((self.raw, 11))
        
        self.puerto_serial.reset_input_buffer()
        print("\nCapturando datos...\n")
        self.puerto_serial.write(b'H')
        
        self.i = 0
        self.puerto_serial.timeout = 0.2
        tiempo_inicio = time.time()
        tiempo_maximo = self.doubleSpinBox_2.value()*1.0  # Tiempo máximo en segundos 

        while self.i < self.raw:
            QCoreApplication.processEvents()
            
            if not self.puerto_serial or not self.puerto_serial.is_open:
                print("El puerto se desconectó durante la adquisición.")
                break

            if time.time() - tiempo_inicio > tiempo_maximo:
                print(f"\n[TIMEOUT]: Se capturaron {self.i} de {self.raw} muestras.")
                break

            try:
                bytes_recibidos = self.puerto_serial.readline()
                if not bytes_recibidos:
                    continue

                rec = bytes_recibidos.decode("utf-8", errors="ignore").strip()
                if not rec:
                    continue

                partes = rec.split()
                valores = [float(val) for val in partes]
                
                if len(valores) == 11:
                    self.datos[self.i][:] = valores
                    self.i += 1
                    #print(f"[LOG MICRO]: Muestra {self.i} capturada.")
                else:
                    print(f"[LOG MICRO]: valores recibidos: {valores}")

            except ValueError:
                print(f"[ERR CONVERSIÓN]: {rec}")
            except Exception as e:
                print(f"Error durante la lectura: {e}")
                break

    def ListarPuertos(self):
        combo = self.comboBox 
        combo.clear()
        
        puertos = serial.tools.list_ports.comports()
        
        if puertos:
            for puerto in puertos:
                combo.addItem(f"{puerto.device} - {puerto.description}", userData=puerto.device)

            self.pushButton_2.setEnabled(True)
            self.comboBox_2.setEnabled(True)
            self.comboBox_2.clear()
            self.comboBox_2.addItem("9600", userData=9600)
            self.comboBox_2.addItem("115200", userData=115200)
            self.comboBox_2.setCurrentIndex(0)
            self.doubleSpinBox.setEnabled(True)
            self.doubleSpinBox.setValue(0.5)
                
        else:
            combo.addItem("No hay puertos disponibles")
            self.pushButton_2.setEnabled(False)
            self.comboBox_2.setEnabled(False)
            self.comboBox_2.clear()
            self.doubleSpinBox.setEnabled(False)

    def ObtenerPuertoSeleccionado(self):
        return self.comboBox.currentData()

    def on_combobox_click(self):
        self.ListarPuertos()
        QComboBox.showPopup(self.comboBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Integran tes: <br />Diego Alejandro Arellano Gutierrez - 110847<br />Edwar Felipe García Patiño - 142911<br />Javier Bohorquez Gaitán - 98587<br />Johan Montejo - 124077<br />Sergio Iván Jaimes Garzón - 133238</p></body></html>"))
        self.groupBox.setTitle(_translate("Form", "Datos No Calibrados "))
        self.label_4.setText(_translate("Form", "Giroscopio"))
        self.label_5.setText(_translate("Form", "Acelerometro"))
        self.label_6.setText(_translate("Form", "Magnetometro"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/UNIVERSIDAD_ECCI.png\" width=\"150\"/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">MPU9250 - ADQUISICION, CALIBRACION Y GRAFICACION DE DATOS</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Form", "Datos Calibrados "))
        self.label_7.setText(_translate("Form", "Giroscopio"))
        self.label_8.setText(_translate("Form", "Acelerometro"))
        self.label_9.setText(_translate("Form", "Magnetometro"))
        self.groupBox_3.setTitle(_translate("Form", "Ángulos de Euler"))
        self.groupBox_4.setTitle(_translate("Form", "Comunicación Serial"))
        self.label_13.setText(_translate("Form", "Velocidad"))
        self.label_14.setText(_translate("Form", "Timeout"))
        self.pushButton_3.setText(_translate("Form", "Desconectar"))
        self.pushButton_2.setText(_translate("Form", "Conectar"))
        self.groupBox_5.setTitle(_translate("Form", "Monitor Serial"))
        self.pushButton_4.setText(_translate("Form", "Giro/Acel"))
        self.pushButton.setText(_translate("Form", "Magn"))
        self.pushButton_8.setText(_translate("Form", "Giro/Acel/Magn"))
        self.pushButton_6.setText(_translate("Form", "Giro/Acel"))
        self.pushButton_7.setText(_translate("Form", "Magn X"))
        self.pushButton_5.setText(_translate("Form", "Magn Y"))
        self.pushButton_9.setText(_translate("Form", "Magn Z"))
        self.pushButton_10.setText(_translate("Form", "Graficar Calibraciones"))
        self.label_15.setText(_translate("Form", "N. Muestras"))
        self.label_16.setText(_translate("Form", "T. Max (s)"))
        self.label_17.setText(_translate("Form", "Calibrar: "))
        self.label_18.setText(_translate("Form", "Adquirir: "))

# ------------------------------------------------------------
#               MAIN
# ------------------------------------------------------------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
