# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-Taller1-MPU9250.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QComboBox
import serial
import serial.tools.list_ports  # <-- Agrega esta línea
import numpy 
import matplotlib.pyplot as plt
import numpy.matlib as npm
from copy import copy, deepcopy
import time
import sys


class OutputRedirector:
    def __init__(self, text_widget):
        self.text_widget = text_widget
        self.stdout_orig = sys.stdout  # Guardar la consola original

    def write(self, text):
        # 1. Mantener la salida en la consola de VS Code/Terminal
        self.stdout_orig.write(text)
        
        # 2. Escribir en el QPlainTextEdit de la GUI si el texto no está vacío
        if text.strip():
            # Insertar texto al final del log
            self.text_widget.moveCursor(self.text_widget.textCursor().MoveOperation.End)
            self.text_widget.insertPlainText(text + "\n")
            self.text_widget.moveCursor(self.text_widget.textCursor().MoveOperation.End)

    def flush(self):
        # Requerido para compatibilidad con sys.stdout
        self.stdout_orig.flush()
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1072, 701)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(720, 560, 221, 121))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 331, 631))
        self.groupBox.setObjectName("groupBox")
        self.GiroscopioNoCalibrado = PlotWidget(self.groupBox)
        self.GiroscopioNoCalibrado.setGeometry(QtCore.QRect(20, 40, 291, 171))
        self.GiroscopioNoCalibrado.setObjectName("GiroscopioNoCalibrado")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 420, 71, 16))
        self.label_6.setObjectName("label_6")
        self.AcelerometroNoCalibrado = PlotWidget(self.groupBox)
        self.AcelerometroNoCalibrado.setGeometry(QtCore.QRect(20, 240, 291, 171))
        self.AcelerometroNoCalibrado.setObjectName("AcelerometroNoCalibrado")
        self.MagnetometroNoCalibrado = PlotWidget(self.groupBox)
        self.MagnetometroNoCalibrado.setGeometry(QtCore.QRect(20, 440, 291, 171))
        self.MagnetometroNoCalibrado.setObjectName("MagnetometroNoCalibrado")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 301, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 1071, 31))
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 50, 331, 631))
        self.groupBox_2.setObjectName("groupBox_2")
        self.GiroscopioNoCalibrado_2 = PlotWidget(self.groupBox_2)
        self.GiroscopioNoCalibrado_2.setGeometry(QtCore.QRect(20, 40, 291, 171))
        self.GiroscopioNoCalibrado_2.setObjectName("GiroscopioNoCalibrado_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 220, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 71, 16))
        self.label_9.setObjectName("label_9")
        self.AcelerometroNoCalibrado_2 = PlotWidget(self.groupBox_2)
        self.AcelerometroNoCalibrado_2.setGeometry(QtCore.QRect(20, 240, 291, 171))
        self.AcelerometroNoCalibrado_2.setObjectName("AcelerometroNoCalibrado_2")
        self.MagnetometroNoCalibrado_2 = PlotWidget(self.groupBox_2)
        self.MagnetometroNoCalibrado_2.setGeometry(QtCore.QRect(20, 440, 291, 171))
        self.MagnetometroNoCalibrado_2.setObjectName("MagnetometroNoCalibrado_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 360, 331, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.GiroscopioNoCalibrado_4 = PlotWidget(self.groupBox_3)
        self.GiroscopioNoCalibrado_4.setGeometry(QtCore.QRect(20, 30, 291, 191))
        self.GiroscopioNoCalibrado_4.setObjectName("GiroscopioNoCalibrado_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(720, 50, 331, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 53))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(720, 160, 331, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 60, 291, 111))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 291, 23))
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.groupBox.raise_()
        self.label_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.label_2.raise_()



        self.puerto_serial = None
        self.groupBox.setEnabled(False)
        self.groupBox_2.setEnabled(False)
        self.groupBox_3.setEnabled(False)
        self.groupBox_5.setEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        sys.stdout = OutputRedirector(self.plainTextEdit)
        self.comboBox.showPopup = self.on_combobox_click
        self.pushButton.setEnabled(False)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.clicked.connect(self.ConectarPuerto)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.clicked.connect(self.DesconectarPuerto)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def ListarPuertos(self):    
        # Acceso directo porque estás dentro de Ui_Form
        combo = self.comboBox 
        combo.clear()
        
        puertos = serial.tools.list_ports.comports()
        
        if puertos:
            for puerto in puertos:
                combo.addItem(f"{puerto.device} - {puerto.description}", userData=puerto.device)
                self.pushButton_2.setEnabled(True)
        else:
            combo.addItem("No hay puertos disponibles")
            self.pushButton_2.setEnabled(False)

    def ConectarPuerto(self):
        self.groupBox_5.setEnabled(True)

        if not self.puerto_serial or not self.puerto_serial.is_open:
            # Obtener el nombre limpio del puerto (ej: 'COM3')
            puerto_nom = self.ObtenerPuertoSeleccionado()
            
            # Validar selección
            if not puerto_nom or puerto_nom == "No hay puertos disponibles":
                print("Selecciona un puerto válido antes de conectar.")
                return

            try:
                # Configurar y abrir puerto I2C/UART (Ajusta los baudios según tu micro, ej: 115200)
                self.puerto_serial = serial.Serial(
                    port=puerto_nom,
                    baudrate=115200,
                    timeout=0.1
                )
                
                # Actualizar interfaz
                self.pushButton.setEnabled(True)
                self.pushButton_2.setEnabled(False)
                self.pushButton_3.setEnabled(True)
                self.comboBox.setEnabled(False) # Bloquea el selector mientras está conectado
                
                print(f"--- Conectado exitosamente a {puerto_nom} ---")

            except serial.SerialException as e:
                print(f"Error al abrir el puerto {puerto_nom}: {e}")

    def DesconectarPuerto(self):
        if self.puerto_serial and self.puerto_serial.is_open:
            try:
                self.puerto_serial.close()
                self.puerto_serial = None
                
                # Actualizar interfaz
                self.comboBox.setEnabled(True)
                self.pushButton.setEnabled(False)
                self.pushButton_2.setEnabled(True)
                self.pushButton_3.setEnabled(False)
                print("--- Puerto Desconectado ---")
            except Exception as e:
                print(f"Error al cerrar el puerto: {e}")

    def ObtenerPuertoSeleccionado(self):
        """Retorna solo el nombre del puerto (ej: 'COM3') para la conexión serial."""
        return self.comboBox.currentData()

    def on_combobox_click(self):
        self.ListarPuertos()
        # Llama a showPopup del widget directamente pasando self.comboBox
        QComboBox.showPopup(self.comboBox)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Integrantes: <br />Diego Alejandro Arellano Gutierrez - 110847<br />Edwar Felipe García Patiño - 142911<br />Javier Bohorquez Gaitán - 98587<br />Johan Montejo - 124077<br />Sergio Iván Jaimes Garzón - 133238</p></body></html>"))
        self.groupBox.setTitle(_translate("Form", "Datos No Calibrados "))
        self.label_4.setText(_translate("Form", "Giroscopio"))
        self.label_5.setText(_translate("Form", "Acelerometro"))
        self.label_6.setText(_translate("Form", "Magnetometro"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/UNIVERSIDAD_ECCI.png\" width=\"150\"/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">MPU9250 - ADQUISICION, CALIBRACION Y GRAFICACION DE DATOS</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Form", "Datos Calibrados "))
        self.label_7.setText(_translate("Form", "Giroscopio"))
        self.label_8.setText(_translate("Form", "Acelerometro"))
        self.label_9.setText(_translate("Form", "Magnetometro"))
        self.groupBox_3.setTitle(_translate("Form", "Ángulos de Euler"))
        self.groupBox_4.setTitle(_translate("Form", "Comunicación Serial"))
        self.pushButton_3.setText(_translate("Form", "Desconectar"))
        self.pushButton_2.setText(_translate("Form", "Conectar"))
        self.groupBox_5.setTitle(_translate("Form", "Monitor Serial"))
        self.pushButton.setText(_translate("Form", "Adquirir Datos"))
from pyqtgraph import PlotWidget
import IMG_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
